# Generated by Django 5.0.6 on 2024-07-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTesting_Scan',
            fields=[
                ('testing_id', models.AutoField(primary_key=True, serialize=False)),
                ('scan_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
