# Generated by Django 5.0.6 on 2024-07-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtesting_scan',
            name='scan_image',
            field=models.ImageField(upload_to='foodscan/'),
        ),
    ]
