# Generated by Django 5.0.6 on 2024-08-04 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='diabetes_barcode',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode_number', models.CharField(default='default_value', max_length=255)),
                ('result_data', models.TextField()),
                ('reason_data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_response', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
