# Generated by Django 5.0.6 on 2024-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes_barcode',
            name='calcium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='iron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='saturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetes_barcode',
            name='vitamin_c',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
