# Generated by Django 5.0.6 on 2024-08-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_algorithm', '0002_diabetes_barcode_calcium_diabetes_barcode_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes_barcode',
            name='unhealthy_data',
            field=models.TextField(default=None),
        ),
    ]
