# Generated by Django 5.0.6 on 2024-08-15 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('disease_algorithm', '0003_diabetes_barcode_unhealthy_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode_bot',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='default_value', max_length=255)),
                ('bot_response', models.TextField()),
                ('user_barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_bot', to='disease_algorithm.diabetes_barcode')),
            ],
        ),
    ]
