name: Check Secrets on Push

on:
  push:
    branches:
      - main  # You can change this to target specific branches
jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install trufflehog or secretlint (you can choose one based on your preference)
      - name: Install trufflehog
        run: |
          pip install trufflehog

      # Scan the repository for secrets
      - name: Scan for secrets with trufflehog
        run: |
          trufflehog filesystem --no-update --json . || echo "No secrets found."
